"use client";
import type { Metadata } from "next";
import "./globals.css";
import "leaflet/dist/leaflet.css";
import { Poppins } from "next/font/google";
import { UserProvider, useUser } from "@/context/userContext";
import React from "react";
import { DisasterProvider } from "@/context/disasterContext";
import { ResourceProvider } from "@/context/resourcesContext";
import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Inner wrapper to access User context
const RootContent = ({ children }: { children: React.ReactNode }) => {
  const { loading } = useUser();

  if (loading) {
    // You can replace this with a spinner or skeleton
    return (
      <div className="flex items-center justify-center h-screen w-screen">
        <p>Loading data...</p>
      </div>
    );
  }

  return <>{children}</>;
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <UserProvider>
          <DisasterProvider>
            <ResourceProvider>
              <RootContent>
                {children}
                <Toaster />
              </RootContent>
            </ResourceProvider>
          </DisasterProvider>
        </UserProvider>
      </body>
    </html>
  );
}
